nginx:
  build: "nginx"
  ports:
    - "5000:5000"
    - "5001:5001"
    - "5002:5002"
    - "5011:5011"
    - "5440:5440"
    - "5441:5441"
    - "5442:5442"
    - "5443:5443"
    - "5444:5444"
    - "5445:5445"
    - "5446:5446"
    - "5447:5447"
    - "5448:5448"
  links:
    - registryv1:registryv1
    - registryv2:registryv2
    - notaryserverhttp:notaryserverhttp
registryv1:
  image: registry:0.9.1
  ports:
    - "5000"
registryv2:
  image: registry:2.0.1
  ports:
    - "5000"
notaryserver:
  image: distribution/notary_notaryserver:0.1.4
  ports:
   - "8080"
   - "4443:4443"
  volumes:
   - notary-server/notary-config.json:/go/src/github.com/docker/notary/cmd/notary-server/config.json:ro
   - notary-server/certs:/certs:ro
notaryserverhttp:
  image: distribution/notary_notaryserver:0.1.4
  ports:
   - "8080"
   - "4443"
  volumes:
   - notary-server/notary-http-config.json:/go/src/github.com/docker/notary/cmd/notary-server/config.json:ro
   - notary-server/certs:/certs:ro
