nginx:
  build: "nginx"
  ports:
    - "5000:5000"
    - "5001:5001"
    - "5002:5002"
    - "5011:5011"
    - "5440:5440"
    - "5441:5441"
    - "5442:5442"
    - "5443:5443"
    - "5444:5444"
    - "5445:5445"
    - "5446:5446"
    - "5447:5447"
    - "5448:5448"
  links:
    - registryv1:registryv1
    - registryv2:registryv2
registryv1:
  image: golem-registry:latest
  ports:
    - "5000"
registryv2:
  image: golem-distribution:latest
  ports:
    - "5000"
registryv2token:
  image: golem-distribution:latest
  ports:
    - "5554:5000"
    - "5555:5000"
  volumes:
    - tokenserver/registry-config.yml:/etc/docker/registry/config.yml
    - tokenserver/certs/localregistry.cert:/etc/docker/registry/localregistry.cert
    - tokenserver/certs/localregistry.key:/etc/docker/registry/localregistry.key
    - tokenserver/certs/signing.cert:/etc/docker/registry/tokenbundle.pem
tokenserver:
  build: "tokenserver"
  command: "--debug -addr 0.0.0.0:5556 -issuer registry-test -passwd .htpasswd -tlscert tls.cert -tlskey tls.key -key sign.key -realm http://auth.localregistry:5556"
  ports:
    - "5556:5556"
malevolent:
  build: "malevolent"
  command: "-l 0.0.0.0:6666 -r http://registryv2:5000 -c /certs/localregistry.cert -k /certs/localregistry.key"
  links:
    - registryv2:registryv2
  volumes:
   - malevolent/certs:/certs:ro
  ports:
   - "6666:6666"
